- name: copy host resolver
  template: src=hosts.j2 dest=/etc/hosts
  
- name: install ppa
  apt_repository:
    repo: ppa:tohojo/flent

- name: install package
  apt:
    pkg:
      - netperf
      - flent
      - python3
      - python3-pip
    update_cache: yes

- name: upgrade pip
  shell: pip3 install --upgrade pip

- name: install python packages
  pip:
    executable: pip3
    name:
      - pandas
      - matplotlib

- name: Create a directory
  file:
    path: /root/flent/
    state: directory

- name: Create a directory
  file:
    path: /root/flent/{{ scenario }}
    state: directory

- name: Create a directory
  file:
    path: /root/flent/{{ scenario }}/rrul
    state: directory

- name: Create a directory
  file:
    path: /root/flent/{{ scenario }}/tcp_upload
    state: directory

- name: Create a directory
  file:
    path: /root/flent/{{ scenario }}/tcp_download
    state: directory

- name: copy bash test
  template: src=test.sh.j2 dest=/root/flent/test.sh

- name: copy python
  template: src=rrul_graphic.py.j2 dest=/root/flent/rrul_graphic.py

- name: copy python
  template: src=tcp_download_graphic.py.j2 dest=/root/flent/tcp_download_graphic.py

- name: copy python
  template: src=tcp_upload_graphic.py.j2 dest=/root/flent/tcp_upload_graphic.py

- name: copy bash
  template: src=generate_graphic.sh.j2 dest=/root/flent/generate_graphic.sh