- name: sleep
  pause:
    seconds: 10

- name: run script
  shell: bash /root/flent/generate_graphic.sh
  environment:
    type: "{{ type }}"
    scenario: "{{ scenario }}"
    ovnovs: "{{ ovnovs }}"


- name: ansible copy {{ ovnovs }}_{{ ansible_hostname }}_{{ scenario }}_{{ type }}.png
  fetch:
    src: /root/flent/{{ scenario }}/{{ type }}/{{ ovnovs }}_{{ ansible_hostname }}_{{ scenario }}_{{ type }}.png
    dest: /root/flent/{{ scenario }}/{{ type }}/
    flat: yes